---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: {{ .Values.environmentName }}-tf
spec:
  interval: 1m
  url: {{ .Values.git.url}}
  ref:
    branch: main
---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: {{ .Values.environmentName }}-tf
spec:
  path: {{ .Values.git.path}}
  approvePlan: auto
  interval: 1m
  
  varsFrom:
  - kind: Secret
    name: aws
    varsKeys: 
    - access_key
  - kind: Secret
    name: aws
    varsKeys: 
    - secret_key
  values: {{ .Values.tfValues }}
  sourceRef:
    kind: GitRepository
    name: {{ .Values.environmentName }}-tf
  writeOutputsToSecret:
    name: {{ .Values.environmentName }}-outputs
